version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
      nodejs: 10
      nodejs: 12
    commands:
      - apt-get install -y yarn
  preBuild:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
artifacts:
  baseDirectory: build
  files:
    - "**/*"
cache:
  paths:
    - node_modules/**/*
