version: 0.1
frontend:
  phases:
    install:
      - commands:
        - apt update -y
        - apt-get install -y yarn
    preBuild:
      commands:
        - yarn install
    build:
      runtime-versions:
        nodejs: 10
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
