version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      nodejs: 14
    commands:
      - apt-get update -y
      - apt-get install -y yarn
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
artifacts:
  files:
    - "**/*"
  base-directory: build
cache:
  paths:
    - node_modules/**/*
